Repository mundipagg/boleto-api, pull requests merged in 2021-11, with the labels that each got.

#267 [BPROC-246] - Layout de boleto JPMorgan
  boleto/config.go
  boleto/html.go
  boleto/logos.go
  boleto/templateJPMorgan.go
Labels: Banking

#264 [BPROC-232] - Registro de boleto JPMorgan na boleto-api
  .gitignore
  api/errors.go
  api/errors_test.go
  api/erros_test.go
  app/app.go
  app/app_test.go
  bank/bank.go
  bank/bank_test.go
  bank/services/jpmorgan/contracts.go
  bank/services/jpmorgan/jpmorgan.go
  bank/services/jpmorgan/jpmorgan_test.go
  bank/services/jpmorgan/stub.go
  bb/bb.go
  boleto/config.go
  boleto/html.go
  boleto/logos.go
  boleto/templateJPMorgan.go
  bradescoNetEmpresa/bradescoNetEmpresa.go
  bradescoShopFacil/bradescoShopFacil.go
  caixa/caixa.go
  certificate/blob.go
  certificate/certificateTypes.go
  certificate/mock.go
  citibank/citi.go
  config/config.go
  env/install.go
  infrastructure/token/jwt.go
  infrastructure/token/rs256.go
  itau/itau.go
  itau/itau_test.go
  mock/jpmorgan.go
  mock/mock.go
  models/boleto.go
  pefisa/pefisa.go
  santander/santander.go
  stone/stone.go
  test/stub.go
  tmpl/funcmaps.go
  tmpl/funcmaps_test.go
  util/http.go
Labels: Banking

#262 [BPROC-237] - Instalação dos certificados de transporte e autenticação da JPMorgan na boleto-api
  .gitignore
  app/app.go
  app/app_test.go
  bank/bank_test.go
  certificate/blob.go
  certificate/certificateTypes.go
  certificate/mock.go
  citibank/citi.go
  config/config.go
  env/install.go
  infrastructure/token/jwt.go
  infrastructure/token/rs256.go
  itau/itau_test.go
  santander/santander.go
  util/http.go
Labels: enhancement, Banking, feature

#272 [BPROC-285] Melhoria de logs - Falhas de Segurança
  util/http.go
  util/http_test.go
Labels: bug, Banking

#273 [BPROC-294] Adiciona zeros ao NossoNumero JPMorgan
  bank/services/jpmorgan/contracts.go
  bank/services/jpmorgan/jpmorgan.go
  bank/services/jpmorgan/jpmorgan_test.go
  mock/jpmorgan.go
Labels: bug, Banking
